POST http://localhost:3000/register
Content-Type: application/json
[
    {
        "username": "johndoe",
        "name": "John Doe",
        "age": 21,
        "email": "johndoe@gmail.com",
        "password": "milugo45"
    },
]